
const path = require('path');
const expect = require('chai').expect;
const execa = require('execa');

describe('command:dx', () => {
  const cli = path.join(__dirname, '../../bin/dx.js');

  describe('autogenerated version', () => {
    const expectedVersion = require('../../package.json').version;
    let commandResult;

    before(async () => {
      commandResult = await execa('node', [cli, '--version'])
    });

    it('succeeds', () => {
      expect(commandResult.exitCode).to.equal(0);
    });

    it('returns expected version string', () => {
      expect(commandResult.stdout).to.contain(expectedVersion);
    });
  });

  describe('autogenerated help', () => {
    let commandResult;

    before(async () => {
      commandResult = await execa('node', [cli, '--help'])
    });

    it('finished with success', () => {
      expect(commandResult.exitCode).to.equal(0);
    });

    const expectedSubcommands = [
      'add',
      'init',
      'stack',
    ];
    expectedSubcommands.forEach(s => {
      it(`contains the ${s} subcommand`, () => {
        expect(commandResult.stdout).to.contain(s);
      });
    });
  });

});
